#!/usr/bin/env python3
"""Concurrent-write robustness simulation harness for forge-wiki `fw.py`.

Permanent regression anchor. Honest measurement: failures are findings, never fudged.

Design:
- A bare git repo acts as origin (INDEX.md + notes/ signals/ handoff/ seed content).
- N clones = N concurrent units (machines/agents), run as REAL parallel OS
  processes (subprocess.Popen of this same script in `worker` mode).
- Each unit loop (per file, 2-3 files/unit):
    create signals/signal_<date>_unit{i}_{seq}.md (with frontmatter)
    -> python3 fw.py sync --write -> commit -> push
    -> on push reject: git pull --no-rebase (merge);
       on conflict: INDEX.md -> checkout one side + fw sync --write regen,
                    other files -> both-keep (strip markers, keep both sides);
       commit -> push. Max 10 retries per file; give-ups recorded honestly.
- Pollution scenarios (separate runs): (a) broken-frontmatter + binary junk .md
  (b) INDEX.md truncation pushed (c) AUTO markers deleted. Each measures whether
  subsequent units' sync/heal recovers.
- Scales: N=2,5,10,25 (reps=1), N=50 (reps=3 — borderline measurement discipline).

Mechanical metrics per run (JSON):
  lost_update      — every unit-written file present in final origin ls-files?
  index_integrity  — AUTO-INDEX:START count==1, conflict markers==0, fw check rc
  history_markers  — committed conflict markers in history (git log -S "<<<<<<<")
  retries          — per-push retry distribution + give-ups
  wall_time        — per run

Usage:
  python3 sim_concurrency.py all --workdir DIR          # full suite -> report data
  python3 sim_concurrency.py scale N [reps] --workdir DIR
  python3 sim_concurrency.py pollute {a|b|c} --workdir DIR
  python3 sim_concurrency.py worker <clone_dir> <unit_id> <nfiles> <result_json>
"""

import json
import os
import random
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

FW = str(Path(__file__).resolve().parent.parent / "bin" / "fw.py")
DATE = "2026-07-18"
START_MARK = "<!-- AUTO-INDEX:START"
# Content-first (deferred-index) pushes carry no conflict-resolution cost — a retry
# is just wait+pull+push — so the cap is a liveness budget, not a safety bound.
# 30 × backoff(ceil 2s) ≈ 60s worst-case wait: acceptable for wiki writes.
# Per-write-sync mode keeps the tighter historical cap for A/B comparability.
MAX_RETRIES = 10 if os.environ.get("FW_SIM_SYNC_PER_WRITE") == "1" else int(os.environ.get("FW_SIM_MAX_RETRIES", "30"))

# ---------------------------------------------------------------- helpers

def sh(args, cwd=None, check=True, env=None):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True, env=env)
    if check and r.returncode != 0:
        raise RuntimeError(f"cmd {args} rc={r.returncode}\nstdout:{r.stdout}\nstderr:{r.stderr}")
    return r


def git(cwd, *args, check=True):
    return sh(["git", "-c", "user.name=sim", "-c", "user.email=sim@local",
               *args], cwd=cwd, check=check)


# ---------------------------------------------------------------- setup

SEED_INDEX = """# Sim Wiki — INDEX

Curated pointers (human-owned):
- `notes/note_2026-07-01_seed.md` — seed note
- Live pointer: signals section holds unit results.

<!-- AUTO-INDEX:START (generated by fw.py — do not hand-edit inside) -->
> Derived — regenerate with `fw sync --write`; conflicts here heal by regeneration (`fw heal --write`). Last sync: 2026-07-17.
<!-- AUTO-INDEX:END -->

Curated footer line (must survive everything).
"""


def make_origin(workdir: Path) -> Path:
    origin = workdir / "origin.git"
    seed = workdir / "seed"
    for p in (origin, seed):
        shutil.rmtree(p, ignore_errors=True)
    origin.mkdir(parents=True)
    sh(["git", "init", "--bare", "-b", "main", str(origin)])
    seed.mkdir()
    git(seed, "init", "-b", "main")
    (seed / "INDEX.md").write_text(SEED_INDEX)
    for section, names in {
        "notes": ["note_2026-07-01_seed.md", "note_2026-07-10_plan.md"],
        "signals": ["signal_2026-07-15_seed.md"],
        "handoff": ["handoff_2026-07-16_seed.md"],
    }.items():
        d = seed / section
        d.mkdir()
        for n in names:
            (d / n).write_text(
                f"---\ndescription: seed file {n}\ntype: seed\n---\n\n# {n}\n\nseed content\n")
    git(seed, "add", "-A")
    git(seed, "commit", "-m", "seed")
    git(seed, "remote", "add", "origin", str(origin))
    git(seed, "push", "origin", "main")
    return origin


# ---------------------------------------------------------------- worker

def resolve_union(path: Path):
    """Both-keep resolution: drop conflict marker lines, keep both sides."""
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
    out = [ln for ln in lines if not re.match(r"^(<{7}|={7}\s*$|>{7}|\|{7})", ln)]
    path.write_text("".join(out), encoding="utf-8")


def fw_sync(clone: Path):
    return subprocess.run([sys.executable, FW, "sync", "--write"], cwd=clone,
                          capture_output=True, text=True)


def worker(clone: str, unit_id: int, nfiles: int, result_json: str):
    clone = Path(clone)
    random.seed(unit_id * 7919 + os.getpid())
    rec = {"unit": unit_id, "files": [], "pushes": [], "sync_rcs": [], "gave_up": []}
    for seq in range(nfiles):
        rel = f"signals/signal_{DATE}_unit{unit_id}_{seq}.md"
        (clone / rel).write_text(
            f"---\ndescription: unit {unit_id} result {seq}\ntype: signal\nunit: {unit_id}\n---\n\n"
            f"# unit{unit_id} result {seq}\n\npayload {random.random()}\n")
        rec["files"].append(rel)
        # Deferred-index mode (design test 2026-07-18): content-first writes — the
        # derived INDEX is NOT regenerated per write, so scoped files cannot conflict
        # and the only contention left is the git ref race itself. One sync pass runs
        # post-hoc (run_scale), matching the "index is a derivation" doctrine and
        # openwiki's post-run middleware. Default ON; FW_SIM_SYNC_PER_WRITE=1 restores
        # the old per-write behavior for A/B measurement.
        if os.environ.get("FW_SIM_SYNC_PER_WRITE") == "1":
            r = fw_sync(clone)
            rec["sync_rcs"].append(r.returncode)
        git(clone, "add", "-A")
        git(clone, "commit", "-m", f"unit{unit_id} file{seq}", check=False)
        retries = 0
        pushed = False
        while retries <= MAX_RETRIES:
            p = git(clone, "push", "origin", "main", check=False)
            if p.returncode == 0:
                pushed = True
                break
            retries += 1
            # F-1 fix (2026-07-18): exponential backoff + jitter BEFORE re-attempt —
            # without it N>=25 units hammer the ref in lockstep and walk to the cap.
            # This sleep is the product's documented retry recipe (SPEC §3), not sim-only.
            time.sleep(min(0.05 * (2 ** retries), 2.0) * random.uniform(0.5, 1.5))
            pull = git(clone, "pull", "--no-rebase", "--no-edit", "origin", "main", check=False)
            conflicted = git(clone, "diff", "--name-only", "--diff-filter=U",
                             check=False).stdout.split()
            if conflicted:
                for f in conflicted:
                    if f == "INDEX.md":
                        # arbitrary side, then regenerate (index = derivation, not state)
                        side = random.choice(["--ours", "--theirs"])
                        c = git(clone, "checkout", side, "--", "INDEX.md", check=False)
                        if c.returncode != 0:
                            git(clone, "checkout", "--ours" if side == "--theirs" else "--theirs",
                                "--", "INDEX.md", check=False)
                    else:
                        resolve_union(clone / f)
                r2 = fw_sync(clone)
                rec["sync_rcs"].append(r2.returncode)
                git(clone, "add", "-A")
                git(clone, "commit", "--no-edit", check=False)
            elif pull.returncode != 0:
                # non-conflict pull failure (e.g. concurrent ref update) — brief backoff
                time.sleep(random.uniform(0.02, 0.15))
        rec["pushes"].append({"file": rel, "retries": retries, "pushed": pushed})
        if not pushed:
            rec["gave_up"].append(rel)
    Path(result_json).write_text(json.dumps(rec))


# ---------------------------------------------------------------- measurement

def measure(workdir: Path, origin: Path, unit_recs: list, label: str,
            wall: float, extra=None) -> dict:
    insp = workdir / f"inspect_{label}"
    shutil.rmtree(insp, ignore_errors=True)
    git(workdir, "clone", "-q", str(origin), str(insp))
    ls = git(insp, "ls-files").stdout.split()
    expected = [f for r in unit_recs for f in r["files"]]
    gave_up = [f for r in unit_recs for f in r.get("gave_up", [])]
    missing = [f for f in expected if f not in ls]
    lost = [f for f in missing if f not in gave_up]  # pushed-but-lost = true lost update
    idx = (insp / "INDEX.md").read_text(encoding="utf-8", errors="replace")
    starts = idx.count(START_MARK)
    conflict_markers = len(re.findall(r"^(<{7}|={7}|>{7})", idx, re.M))
    chk = subprocess.run([sys.executable, FW, "check"], cwd=insp,
                         capture_output=True, text=True)
    hist = git(insp, "log", "--oneline", "-S", "<<<<<<<", check=False).stdout.strip()
    hist_markers = len(hist.splitlines()) if hist else 0
    retries = [p["retries"] for r in unit_recs for p in r["pushes"]]
    res = {
        "label": label,
        "units": len(unit_recs),
        "files_expected": len(expected),
        "files_in_origin": len([f for f in expected if f in ls]),
        "gave_up_after_max_retries": gave_up,
        "lost_updates_pushed_but_missing": lost,
        "index_auto_start_count": starts,
        "index_conflict_markers": conflict_markers,
        "fw_check_rc": chk.returncode,
        "fw_check_out": (chk.stdout + chk.stderr).strip(),
        "history_commits_with_markers": hist_markers,
        "retries_total": sum(retries),
        "retries_max": max(retries) if retries else 0,
        "retries_dist": {str(k): retries.count(k) for k in sorted(set(retries))},
        "wall_time_s": round(wall, 2),
    }
    if extra:
        res.update(extra)
    return res


# ---------------------------------------------------------------- runners

def run_units(workdir: Path, origin: Path, n: int, tag: str,
              pre=None) -> list:
    """Spawn n parallel worker processes; return their result records."""
    procs, recs = [], []
    clones_dir = workdir / f"clones_{tag}"
    shutil.rmtree(clones_dir, ignore_errors=True)
    clones_dir.mkdir()
    for i in range(n):
        clone = clones_dir / f"u{i}"
        git(workdir, "clone", "-q", str(origin), str(clone))
    if pre:
        pre(clones_dir)  # pollution hook operates on already-made clones
    for i in range(n):
        clone = clones_dir / f"u{i}"
        rj = clones_dir / f"result_{i}.json"
        procs.append(subprocess.Popen(
            [sys.executable, __file__, "worker", str(clone), str(i),
             str(2 + i % 2), str(rj)]))
    for p in procs:
        p.wait()
    for i in range(n):
        rj = clones_dir / f"result_{i}.json"
        if rj.exists():
            recs.append(json.loads(rj.read_text()))
        else:
            recs.append({"unit": i, "files": [], "pushes": [], "gave_up": [],
                         "worker_crashed": True})
    return recs


def run_scale(workdir: Path, n: int, rep: int) -> dict:
    label = f"scale_n{n}_rep{rep}"
    origin = make_origin(workdir)
    t0 = time.time()
    recs = run_units(workdir, origin, n, label)
    # post-hoc single index pass (the deferred half of content-first writes)
    finisher = workdir / f"clones_{label}" / "finisher"
    git(workdir, "clone", "-q", str(origin), str(finisher))
    fw_sync(finisher)
    git(finisher, "add", "-A")
    git(finisher, "commit", "-m", "index: post-hoc sync pass", check=False)
    git(finisher, "push", "origin", "main", check=False)
    res = measure(workdir, origin, recs, label, time.time() - t0)
    crashed = [r["unit"] for r in recs if r.get("worker_crashed")]
    if crashed:
        res["worker_crashed_units"] = crashed
    return res


def run_pollution(workdir: Path, scenario: str) -> dict:
    """3 normal units + 1 polluter (unit 0 acts first, then all race)."""
    origin = make_origin(workdir)
    label = f"pollute_{scenario}"
    pol = workdir / f"polluter_{scenario}"
    shutil.rmtree(pol, ignore_errors=True)
    git(workdir, "clone", "-q", str(origin), str(pol))
    extra = {"scenario": scenario}
    if scenario == "a":  # broken frontmatter + binary junk .md
        (pol / "signals" / f"broken_{DATE}_junk.md").write_text(
            "---\ndescription: unclosed frontmatter\n\nno closing fence\n")
        (pol / "signals" / f"binary_{DATE}_junk.md").write_bytes(
            bytes(random.randrange(256) for _ in range(4096)))
        extra["injected"] = ["signals/broken junk", "signals/binary junk"]
    elif scenario == "b":  # INDEX truncation — wiki destroyed mid-file
        idx = pol / "INDEX.md"
        text = idx.read_text()
        idx.write_text(text[: text.find(START_MARK) + 60])  # cut inside AUTO block, END lost
        extra["injected"] = ["INDEX.md truncated inside AUTO block (END marker lost)"]
    elif scenario == "c":  # AUTO markers deleted entirely
        idx = pol / "INDEX.md"
        lines = [ln for ln in idx.read_text().splitlines(keepends=True)
                 if "AUTO-INDEX" not in ln]
        idx.write_text("".join(lines))
        extra["injected"] = ["AUTO-INDEX START/END markers deleted"]
    git(pol, "add", "-A")
    git(pol, "commit", "-m", f"pollution {scenario}")
    git(pol, "push", "origin", "main")

    t0 = time.time()
    recs = run_units(workdir, origin, 3, label)
    res = measure(workdir, origin, recs, label, time.time() - t0, extra)

    # recovery probe: fresh clone, fw heal --write + sync --write, re-measure
    heal = workdir / f"healprobe_{scenario}"
    shutil.rmtree(heal, ignore_errors=True)
    git(workdir, "clone", "-q", str(origin), str(heal))
    h = subprocess.run([sys.executable, FW, "heal", "--write"], cwd=heal,
                       capture_output=True, text=True)
    s = subprocess.run([sys.executable, FW, "sync", "--write"], cwd=heal,
                       capture_output=True, text=True)
    c = subprocess.run([sys.executable, FW, "check"], cwd=heal,
                       capture_output=True, text=True)
    idx2 = (heal / "INDEX.md").read_text(encoding="utf-8", errors="replace")
    res["heal_probe"] = {
        "heal_rc": h.returncode, "sync_rc": s.returncode, "check_rc": c.returncode,
        "heal_out": (h.stdout + h.stderr).strip()[:400],
        "check_out": (c.stdout + c.stderr).strip()[:200],
        "auto_start_count_after_heal": idx2.count(START_MARK),
        "curated_footer_survived": "Curated footer line" in idx2,
        "curated_header_survived": "Curated pointers" in idx2,
    }
    if scenario == "a":
        lint = subprocess.run([sys.executable, FW, "lint"], cwd=heal,
                              capture_output=True, text=True)
        res["heal_probe"]["lint_out"] = (lint.stdout + lint.stderr).strip()[:400]
    return res


# ---------------------------------------------------------------- main

def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "worker":
        worker(sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[5])
        return
    args = sys.argv[1:]
    mode = args[0] if args else "all"
    wd = Path(args[args.index("--workdir") + 1]) if "--workdir" in args else Path.cwd() / "fw-sim"
    wd.mkdir(parents=True, exist_ok=True)
    results = []
    if mode == "scale":
        n = int(args[1]); reps = int(args[2]) if len(args) > 2 and args[2].isdigit() else 1
        for rep in range(1, reps + 1):
            results.append(run_scale(wd, n, rep))
    elif mode == "pollute":
        results.append(run_pollution(wd, args[1]))
    elif mode == "all":
        for n in (2, 5, 10, 25):
            results.append(run_scale(wd, n, 1))
        for rep in (1, 2, 3):
            results.append(run_scale(wd, 50, rep))
        for sc in ("a", "b", "c"):
            results.append(run_pollution(wd, sc))
    out = wd / f"results_{mode}_{int(time.time())}.json"
    out.write_text(json.dumps(results, indent=2, ensure_ascii=False))
    print(json.dumps(results, indent=2, ensure_ascii=False))
    print(f"\n[raw data] {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
