#!/usr/bin/env bash
# test_closed_ranking.sh — known-pair anchor for "live before closed" in the derived index.
#
# WHY (measured 2026-07-28)
#   `collect()` sorted purely by date. A note stamped `STATUS: SUPERSEDED` therefore outranked its
#   own replacement whenever its filename date happened to be newer — and because the section list
#   is TRUNCATED to PER_SECTION, the closed note did not merely sort high, it CONSUMED one of the
#   visible slots and pushed the live note out of the derived index entirely. A reader saw the
#   superseded item and never learned the live one existed.
#
#   That is an omission, not a cosmetic ordering flaw, which is why this ships with an anchor.
#   The proposition is absorbed from obsidian-mind's supersede module (MIT, breferrari):
#   "retrieval ranks the correction above the thing it corrected."
#
# Lanes
#   P1  closed note is NEWER than the live one → live must still come first
#   P2  with PER_SECTION=1 the single visible slot must go to the LIVE note
#   N1  two live notes → ordinary date-desc order is preserved (the fix must not reorder normal wikis)
#
# Exit 0 = 3/3.  Exit 1 = the ranking regressed.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FW="$ROOT/bin/fw.py"
[ -f "$FW" ] || { echo "FAIL: $FW not found"; exit 1; }

pass=0; fail=0
ok()  { printf '  ✅ %s\n' "$1"; pass=$((pass+1)); }
bad() { printf '  ❌ %s\n' "$1"; fail=$((fail+1)); }

TD="$(mktemp -d)"; trap 'rm -rf "$TD"' EXIT
mkdir -p "$TD/notes"
printf -- '---\ntype: note\ndescription: "live one"\n---\n\nlive body\n' \
  > "$TD/notes/alpha_2026-01-01.md"
printf -- '---\ntype: note\ndescription: "the replaced one"\nstatus: superseded\n---\n\nSTATUS: SUPERSEDED by notes/alpha_2026-01-01.md (2026-01-02)\n' \
  > "$TD/notes/beta_2026-12-31.md"
printf -- '# home\n\n<!-- AUTO-INDEX:START (generated by fw.py — do not hand-edit inside) -->\n<!-- AUTO-INDEX:END -->\n' \
  > "$TD/INDEX.md"

# `fw sync` without --write prints a DRIFT SUMMARY, not the block (the first draft of this anchor
# read that summary and reported "fixture never appeared" — an instrument fault, not a defect).
# Write, then read the block back out of INDEX.md.
_block() {
  ( cd "$TD" && FW_PER_SECTION="${1:-5}" python3 "$FW" sync --write >/dev/null 2>&1 )
  sed -n '/AUTO-INDEX:START/,/AUTO-INDEX:END/p' "$TD/INDEX.md"
}

out=$(_block 5)
live_ln=$(printf '%s\n' "$out" | grep -n 'alpha_2026-01-01' | head -1 | cut -d: -f1)
closed_ln=$(printf '%s\n' "$out" | grep -n 'beta_2026-12-31' | head -1 | cut -d: -f1)
if [ -z "$live_ln" ] || [ -z "$closed_ln" ]; then
  bad "P1 instrument error — one of the fixtures never appeared (live='$live_ln' closed='$closed_ln')"
  printf '%s\n' "$out" | sed 's/^/     /'
elif [ "$live_ln" -lt "$closed_ln" ]; then
  ok "P1 live note outranks the newer CLOSED note"
else
  bad "P1 a SUPERSEDED note outranks its replacement (live line $live_ln, closed line $closed_ln)"
fi

out1=$(_block 1)
if printf '%s\n' "$out1" | grep -q 'alpha_2026-01-01' && ! printf '%s\n' "$out1" | grep -q 'beta_2026-12-31'; then
  ok "P2 the single visible slot goes to the LIVE note (closed note stops evicting it)"
else
  bad "P2 with one slot the index showed the closed note, or dropped the live one"
  printf '%s\n' "$out1" | sed 's/^/     /'
fi

# N1 — the fix must not disturb an ordinary wiki with nothing closed.
rm "$TD/notes/beta_2026-12-31.md"
printf -- '---\ntype: note\ndescription: "newer live"\n---\n\nbody\n' > "$TD/notes/gamma_2026-06-01.md"
outn=$(_block 5)
g_ln=$(printf '%s\n' "$outn" | grep -n 'gamma_2026-06-01' | head -1 | cut -d: -f1)
a_ln=$(printf '%s\n' "$outn" | grep -n 'alpha_2026-01-01' | head -1 | cut -d: -f1)
if [ -n "$g_ln" ] && [ -n "$a_ln" ] && [ "$g_ln" -lt "$a_ln" ]; then
  ok "N1 two live notes keep plain date-desc order (no collateral reordering)"
else
  bad "N1 ordinary date ordering broke (gamma line '$g_ln', alpha line '$a_ln')"
  printf '%s\n' "$outn" | sed 's/^/     /'
fi


# R1 — a RESOLVED/DONE note must NOT be demoted. Cross-family review (gpt-5.5, 2026-07-29) named the
# failing input: stale live notes plus one newly RESOLVED incident postmortem, truncated to N — the
# postmortem is exactly what a reader came for, and demoting the whole CLOSED set hides it.
# Superseding replaces; finishing does not. Without this lane, narrowing the demotion back to the
# full CLOSED set would pass unnoticed.
printf -- '---\ntype: note\ndescription: "settled incident"\nstatus: RESOLVED\n---\n\npostmortem\n' \
  > "$TD/notes/incident_2026-12-30.md"
outr=$(_block 1)
if printf '%s\n' "$outr" | grep -q 'incident_2026-12-30'; then
  ok "R1 a RESOLVED note keeps its date rank (finished is not superseded)"
else
  bad "R1 a RESOLVED note was demoted — the newest settled record is hidden"
  printf '%s\n' "$outr" | sed 's/^/     /'
fi
rm -f "$TD/notes/incident_2026-12-30.md"

echo "----"
echo "superseded-ranking anchor: $pass passed, $fail failed"
[ "$fail" -eq 0 ] || exit 1
